### ISSUE TITLE
Repository links to dead page on os2.eu

### ISSUE THREAD

**Issue by janhalen** [OS2offdig/governance_report_template#19]
The repo description links to https://www.os2.eu/governance which returns a 404.

![image](https://github.com/OS2offdig/governance_report_template/assets/50995332/30da9a23-8d19-43ca-8f19-774fe46c6fa0)

What is the best solution? Remove the link from the repo? 
What should it be replaced with?

Create a placeholder on the webpage?
Containing what content?

**Comment by zorp** [comment]
I have changed the URL on the website so it respond to /governance. FIXED!
