### ISSUE TITLE
Help new projects to adhere to criteria by introducing a sandbox level 

### ISSUE THREAD

**Issue by janhalen** [OS2offdig/governance_report_template#23]
### Obstacle:
Until now there has been a mismatch between the officiel governance model here: https://www.os2.eu/governancemodellen and the governance report template that makes it hard to enforce and inferes risk of ambigous interpretation of product states.

The level "0" in the governance template refers to a set of criterias referenced in the governance model as "minimumskrav".
Furthermore a very ambigous distinction between "projects" and "products" has also been a basis for a unclear strategic and communicative effort from os2 to newcomers and contributors to our community.
There is currently no os2 products considered "level 0" and the criteria are so illusive and basic that is is would be very difficult to distinguish between a "level 0" product and an arbitrarily selected software project somewhere in the whole Open Source ecosystem. As OS2 nowhere states any ambition of patronage of such a broad character, this obstacle needs a review and a change of words.

### Solution background:
After discussions with The Board of Directors of OS2 on the Board Seminar held in january 2024, there was agreement that work should be done one a "sandbox" or "incubating" stage for new products. This has been realized in https://github.com/OS2sandbox/
Furthermore a sandbox stage aligns well with leading Open Source Foundations like Linux Foundation, Eclipse Foundation and Cloud Native Computing Foundation.

### Proposed solution:
All new projects starts the development life-cycle in the os2 sandbox https://github.com/OS2sandbox/ and the criteria for entering this sandbox can be aligned with the "Level 0" or "Minimumskrav" and expanded upon to align with the industry standard. This solutions gives OS2 a way to help new products adhere to the criteria and guide them to eventual maturity before entering "Level 1" as a product.

**Comment by janhalen** [comment]
This change can be made operational in the governance template by changing all occurences of reference to the "non-existant" "Level 0" with a "sandbox" or "sandkasse" reference.

**Comment by zorp** [comment]
Very good solution to the problem. It will enable us to let all code/projects/products that enter the OS2-ecosystem begin in the sandbox. Her we can do the necessary compliance checks before calling anything an OS2-product.
