### ISSUE TITLE
Elaborate on F11 to aling with Standard for Public code and best practice workflows

### ISSUE THREAD

**Issue by janhalen** [OS2offdig/governance_report_template#29]
## Obstacle
While Jira can be a powerful tool for project management and issue tracking, it alone is **not sufficient** for ensuring transparency or quality in the manged codebase.
Having a general goverance criteria that ties the project to a specific closed-source solution like Jira is not best practice and not future proof.

## Rationales
To provide transparency, cooperation and quality control, this criteria should be elaborated to ensure the availability of a public issue tracker and standardized workflow to handle issues.
Without a public issue tracker, contributions from the open-source community may be limited as they lack visibility into existing issues and progress. 
This is what is recommended by the [Standard for Public Code](https://standard.publiccode.net/criteria/) and it is easy to implement by adapting the industry best practices in GitHub Flow or GitLab Flow.

## Proposed Solution
F11 is Elaborated to: "Der anvendes offentlig issue-tracking, hvor der tydeligt henvises til specifikke kodeændringer."

**Comment by janhalen** [comment]
Der anvendes offentlig issue-tracking anvist af OS2, hvor der tydeligt henvises til specifikke kodeændringer.

**Comment by zorp** [comment]
This matches what was agreed upon. Solution approved - closing issue.
