### ISSUE TITLE
Remove part R2 from the governance template

### ISSUE THREAD

**Issue by janhalen** [OS2offdig/governance_report_template#5]
## What part needs to change?
 **Register the unique id of the part of the model this change is about**

R2
 
## Describe the proposed changes to the model: 
**Define if it is an elaboration og the text or a removal of that part of the governance model. And add the proposed elaborations on this part of the goverance model**

As a result of the board-seminar workshop 3 decission on 15-15 january, i propose to remove part R2 on behalf of the board as they find it redundant.

**Comment by zorp** [comment]
The requirement R2 is arbitrary. It is not possible to make an assessment of whether something creates value for others. The requirement is covered by R1 which is about the solution creating local value which to a greater extent is possible to document by virtue of the creator of the product being assumed to also use the product and thereby have made an assessment of the local value creation. Therefore the demand R2 can be deleted.
