### ISSUE TITLE
Change text in headline 

### ISSUE THREAD

**Issue by Tgjerulff** [OS2offdig/governance_report_template#54]
Change text in headline, to ensure broader apeal 

Area: Relevance

Level: 2

From: Niveau 2 – "|    | R3 | _Løsningen har tværkommunal potentiale (anbefaling)_ |"

To: Niveau 2 - Fælles offentlig værdi

**Comment by janhalen** [comment]
This relates to R3 criteria :|    | R3 | _Løsningen har tværkommunal potentiale (anbefaling)_ |

Original issue corrected
