### ISSUE TITLE
Feat: Expand on the template adding a clear and unambiguous reference to the criterias origin

### ISSUE THREAD

**Issue by janhalen** [OS2offdig/governance_report_template#7]
## Add an expanded reference method
 
We need a method to refer each criteria directly to the vision, strategy and or vision of OS2.

**Comment by janhalen** [comment]
References to Foundation for Public code and the business value "support" document is a way to explain the Why and the How.

For reference to Vision and Mission ... should these be added?

**Comment by janhalen** [comment]
Link to mission / vision: https://boks.os2.eu/s/6wBBSjiWT6XiXs6

**Comment by janhalen** [comment]
@zorp: It would be beneficial if the reference page could be built with achors, so linking to each mission value / vision point from the template would be simple and easy.

**Comment by zorp** [comment]
Reflected a bit on this and I think a strategy webpage with the vision and mission is a very generic page. Initiatives change over time and content get deleted, added or updated. So maybe adding anchors is not the way, we could end up having dead links in the governance template.

Or will it be okay that links become obsolete and must be updated in the governance template?

**Comment by zorp** [comment]
The page is now online. https://www.os2.eu/os2s-vision-og-mission

**Comment by janhalen** [comment]
The link in the main template doc should be updated to the new correct link.

**Comment by janhalen** [comment]
Solved in #53
